# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '3'
services:
  db-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER=seed
      - POSTGRES_PASSWORD=super-secret-password
    volumes:
      - $HOME/seed_data:/seed/collected_static
  db-redis:
    image: redis
    volumes:
      - $HOME/seed_data:/seed/collected_static
  web:
    image: ryanmccuaig/seed:skeleton-web
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER=seed
      - POSTGRES_PASSWORD=super-secret-password
      - SEED_ADMIN_USER=user@seed-platform.org
      - SEED_ADMIN_PASSWORD=super-secret-password
      - SEED_ADMIN_ORG=default
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    depends_on:
      - db-redis
      - db-postgres
    volumes:
      - $HOME/seed_data:/seed/collected_static
    ports:
      - "8000:8000"
  web-celery:
    image: ryanmccuaig/seed:skeleton-celery
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER=seed
      - POSTGRES_PASSWORD=super-secret-password
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    depends_on:
      - db-redis
      - db-postgres
      - web
    volumes:
      - $HOME/seed_data:/seed/collected_static
