# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-22 21:00
from __future__ import unicode_literals

from django.db import migrations
import seed.models.properties


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0069_auto_20170614_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='site_eui_ogbs',
            field=seed.models.properties.QuantityField(blank=True, null=True),
        ),
    ]
