# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0070_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystate',
            name='conditioned_floor_area_ogbs',
            field=quantityfield.fields.QuantityField(base_units='ft**2', default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='gross_floor_area_ogbs',
            field=quantityfield.fields.QuantityField(base_units='ft**2', default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='occupied_floor_area_ogbs',
            field=quantityfield.fields.QuantityField(base_units='ft**2', default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='site_eui_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='site_eui_weather_normalized_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='source_eui_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertystate',
            name='source_eui_weather_normalized_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Cycle'),
        ),
        migrations.AlterField(
            model_name='taxlotview',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Cycle'),
        ),
    ]
