# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 23:37
from __future__ import unicode_literals

from django.db import migrations
import quantityfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0071_auto_20170706_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystate',
            name='conditioned_floor_area_ogbs',
            field=quantityfield.fields.QuantityField(base_units='ft**2', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='gross_floor_area_ogbs',
            field=quantityfield.fields.QuantityField(base_units='ft**2', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='occupied_floor_area_ogbs',
            field=quantityfield.fields.QuantityField(base_units='ft**2', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='site_eui_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='site_eui_weather_normalized_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='source_eui_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='source_eui_weather_normalized_ogbs',
            field=quantityfield.fields.QuantityField(base_units='kBTU/ft^2/year', blank=True, null=True),
        ),
    ]
