# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0071_auto_20170721_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='pint_units',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='data_type',
            field=models.IntegerField(choices=[(0, b'raw number'), (1, b'string'), (2, b'date'), (3, b'year'), (4, b'physical quantity')], null=True),
        ),
    ]
