# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 23:10
from __future__ import unicode_literals

from django.db import migrations

def populate_pint_fields(apps, schema_editor):
    """
    Populates the new Pint fields for area and EUI on any existing properties.
    This is a straight-up copy since Imperial units are canonical and so the
    floats are the same; it's just interpreted at the Python layer.
    """
    PropertyState = apps.get_model("seed", "PropertyState")
    for ps in PropertyState.objects.all():
        # rely on pint quantity field settings in the model to serialize
        # correctly to metric
        ps.gross_floor_area_pint              = ps.gross_floor_area
        ps.conditioned_floor_area_pint        = ps.conditioned_floor_area
        ps.occupied_floor_area_pint           = ps.occupied_floor_area
        ps.site_eui_pint                      = ps.site_eui
        ps.source_eui_weather_normalized_pint = ps.source_eui_weather_normalized
        ps.site_eui_weather_normalized_pint   = ps.site_eui_weather_normalized
        ps.source_eui_pint                    = ps.source_eui
        ps.save()

def clear_pint_fields(apps, schema_editor):
    """
    Clears new Pint fields
    """
    PropertyState = apps.get_model("seed", "PropertyState")
    for ps in PropertyState.objects.all():
        ps.gross_floor_area_pint              = None
        ps.conditioned_floor_area_pint        = None
        ps.occupied_floor_area_pint           = None
        ps.site_eui_pint                      = None
        ps.source_eui_weather_normalized_pint = None
        ps.site_eui_weather_normalized_pint   = None
        ps.source_eui_pint                    = None
        ps.save()

class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0072_auto_20170823_1013'),
    ]

    operations = [
        migrations.RunPython(populate_pint_fields, clear_pint_fields),
    ]
