# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 23:10
from __future__ import unicode_literals

from django.db import migrations
from quantityfield import UnitRegistry

ureg = UnitRegistry()
Quantity = ureg.Quantity

def as_area(n):
    if n != None:
        return Quantity(n * ureg('ft**2')).to('m**2').magnitude

def as_eui(n):
    if n != None:
        return Quantity(n * ureg('kBtu/ft**2/year')).to('GJ/m**2/year').magnitude

def populate_si_fields(apps, schema_editor):
    """
    Populates the new SI fields for area ande EUI on any existing properties
    with the converted value of the US customary units fields (which are
    simply floats, implicitly ft**2 and kBtu/ft**2/annum).
    """
    PropertyState = apps.get_model("seed", "PropertyState")
    for ps in PropertyState.objects.all():
        # rely on pint quantity field settings in the model to serialize
        # correctly to metric
        ps.gross_floor_area_si              = as_area(ps.gross_floor_area)
        ps.conditioned_floor_area_si        = as_area(ps.conditioned_floor_area)
        ps.occupied_floor_area              = as_area(ps.occupied_floor_area_si)
        ps.site_eui_si                      = as_eui(ps.site_eui)
        ps.source_eui_weather_normalized_si = as_eui(ps.source_eui_weather_normalized)
        ps.site_eui_weather_normalized_si   = as_eui(ps.site_eui_weather_normalized)
        ps.source_eui_si                    = as_eui(ps.source_eui)
        ps.save()

def clear_si_fields(apps, schema_editor):
    """
    Clears new SI fields
    """
    PropertyState = apps.get_model("seed", "PropertyState")
    for ps in PropertyState.objects.all():
        ps.gross_floor_area_si              = None
        ps.conditioned_floor_area_si        = None
        ps.occupied_floor_area              = None
        ps.site_eui_si                      = None
        ps.source_eui_weather_normalized_si = None
        ps.site_eui_weather_normalized_si   = None
        ps.source_eui_si                    = None
        ps.save()

class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0072_auto_20170818_1602'),
    ]

    operations = [
        migrations.RunPython(populate_si_fields, clear_si_fields),
    ]
