# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0073_auto_20170818_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='units',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
