# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-03 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0075_column_pint_unit'),
        ('seed', '0072_auto_20170829_1047'),
    ]

    operations = [
    ]
