apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web-celery
  name: web-celery
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: web-celery
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: web-celery
    spec:
      containers:
      - args:
        - /seed/docker/start_celery_docker.sh
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.docker
        - name: POSTGRES_DB
          value: seed
        - name: POSTGRES_PASSWORD
          value: super-secret-password
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: seeduser
        - name: SECRET_KEY
          value: <secret>
        image: seedplatform/seed:develop
        imagePullPolicy: Always
        name: web-celery
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /seed/media
          name: seed-media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: seed-media
        persistentVolumeClaim:
          claimName: seed-media
status: {}
