---
- name: extra repos for psql, node
  hosts: all
  become: True
  vars:
    nodejs_version: 8.x
    ansible_distribution_release: trusty
  tasks:
    - lineinfile: name=/etc/apt/sources.list.d/pgdg.list line="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" create=True
    - apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
    - apt_repository: repo={{ item }}
      with_items:
        - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - apt: update_cache=True cache_valid_time=86400


- name: basic config
  hosts: all
  become: True
  tasks:
    - apt: upgrade=True
    - apt: name={{ item }}
      with_items:
        - build-essential
        - curl
        - g++
        - gfortran
        - git
        - libatlas-base-dev
        - libpq-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - mercurial
    - apt: name={{ item }}
      with_items:
        - python-dev
        - python-pip
    - pip: name=pip state=latest
    - pip: name=psycopg2


- name: msg broker
  hosts: all
  become: True
  tasks:
    - apt: upgrade=True update_cache=True cache_valid_time=86400
    - apt: name={{ item }}
      with_items:
        - redis-server


- name: db
  hosts: all
  become: True
  tasks:
    - apt: name=postgresql-9.4 update_cache=True
    # - apt: name=python-psycopg2 # for postgres ansible modules
    - postgresql_user: name=seed-user password=seed-user role_attr_flags=CREATEDB
      become_user: postgres
    - postgresql_db: name=seed-dev owner=seed-user
      become_user: postgres


- name: js
  hosts: all
  become: True
  tasks:
    - apt: name={{ item }}
      with_items:
        - nodejs
        # - npm
    - npm: name={{ item }} global=True
      with_items:
        - bower
        - grunt
    - command: "./bin/install_javascript_dependencies.sh"
      args:
        chdir: /vagrant/repo


- name: django
  hosts: all
  become: True
  tasks:
    - apt: name={{ item }}
      with_items:
        # - python-dev
        - python-enchant # my add, else pip requirements fails later
        - python-numpy
        - python-pip
        - python-scipy
        - uwsgi-core
        - uwsgi-plugin-python
    # - pip: name=pip state=latest
    - pip:
        chdir: /vagrant/repo
        requirements: requirements/local.txt
    - command: "./manage.py {{ item }} --settings=config.settings.dev"
      args:
        chdir: /vagrant/repo
      with_items:
        - migrate
        - create_default_user

